
["General Settings"]
	init_val_starting_level = 1.0

["Attribute 1"]
	display_name = "Vitality : "
	cmd_to_exc = ["/attribute @p generic.max_health base set"]
	on_level_event = ["/effect give @p minecraft:instant_health 2 3"]
	tip_to_display = "§7Represents your overall durability. §7More health means you can survive longer in battle"
	init_val_attribute_one = 20.0
	max_level = 100.0
	base_value_per_point = 1.0
	lock = false

["Attribute 2"]
	display_name = "Attack Power : "
	cmd_to_exc = ["/attribute @p generic.attack_damage base set"]
	on_level_event = [" "]
	tip_to_display = "§7Defines the amount of harm you can inflict with each attack. "
	init_val_attribute_two = 2.0
	max_level = 100.0
	base_value_per_point = 1.0
	lock = false

["Attribute 3"]
	display_name = "Attack Speed : "
	cmd_to_exc = ["/attribute @p generic.attack_speed base set"]
	on_level_event = [" "]
	tip_to_display = "§7Determines how quickly you can swing your weapon. "
	init_val_attribute_three = 4.0
	max_level = 20.0
	base_value_per_point = 1.0
	lock = false

["Attribute 4"]
	display_name = "Protection : "
	cmd_to_exc = ["/attribute @p generic.armor base set [param(0.1)]"]
	on_level_event = [" "]
	tip_to_display = "§7Reduces the amount of damage you take from enemy attacks"
	init_val_attribute_forth = 0.0
	max_level = 200.0
	base_value_per_point = 1.0
	lock = false

["Attribute 5"]
	display_name = "Agility : "
	cmd_to_exc = ["/attribute @p generic.movement_speed base set [param(0.005)]"]
	on_level_event = [" "]
	tip_to_display = "§7Influences how fast you can move"
	init_val_attribute_fifth = 20.0
	max_level = 50.0
	base_value_per_point = 1.0
	lock = false

["Attribute 6"]
	display_name = "Fortitude : "
	cmd_to_exc = ["/attribute @p generic.knockback_resistance base set [param(0.01)]"]
	on_level_event = [" "]
	tip_to_display = "§7Reduces the distance you are pushed back when hit by an enemy or explosion"
	init_val_attribute_sixth = 0.0
	max_level = 100.0
	base_value_per_point = 1.0
	lock = false

["Attribute 7"]
	display_name = "Exploration : "
	cmd_to_exc = ["/attribute @p generic.luck base set [param(0.5)]"]
	on_level_event = [" "]
	tip_to_display = "§7Influences the chances of receiving better loot or triggering beneficial events"
	init_val_attribute_seventh = 0.0
	max_level = 100.0
	base_value_per_point = 1.0
	lock = false

["Attribute 8"]
	display_name = ""
	cmd_to_exc = [" "]
	on_level_event = [" "]
	tip_to_display = ""
	init_val_attribute_eight = 0.0
	max_level = 0.0
	base_value_per_point = 0.0
	lock = true

["Attribute 9"]
	"display_name " = ""
	cmd_to_exc = [" "]
	on_level_event = [" "]
	"tip_to_display " = ""
	init_val_attribute_nine = 0.0
	max_level = 0.0
	base_value_per_point = 0.0
	lock = true

["Attribute 10"]
	"display_name " = ""
	cmd_to_exc = [" "]
	on_level_event = [" "]
	"tip_to_display " = ""
	init_val_attribute_ten = 0.0
	max_level = 0.0
	base_value_per_point = 0.0
	lock = true

